// Starting content. After the first visit it lives in your database and you edit it from /admin.
export const DEFAULT_CONTENT = {
  profile: {
    name: "Christian Ethelbert", first: "Christian", last: "Ethelbert", photo: "", arrows: true,
    callouts: ["2 live projects", "Open to remote roles", "Fortress Bank: live demo", "Next.js + FastAPI + PostgreSQL"],
    role: "Full-stack developer · Abia State, Nigeria",
    tagline: "I build systems that hold up: logins, roles, money and data, shipped end to end.",
    status: "Open to remote roles", email: "christianethelbert1@gmail.com",
    primaryButton: "Hire me", secondaryButton: "See the work",
  },
  labels: {
    ask: { tag: "01 · Ask me", title: "Pick a question." },
    work: { tag: "02 · Work", title: "Three systems, built solo." },
    stack: { tag: "03 · Stack", title: "What I work with." },
    path: { tag: "04 · Path", title: "How I got here." },
    how: { tag: "05 · Principles", title: "How I work." },
    contact: { tag: "06 · Contact", title: "Let's build something that ships." },
  },
  ask: [
    { q: "What do you build?", a: "Full-stack systems where the hard parts matter: authentication, role-based access, payments and consistent data. Fortress Bank (scalable, live and still improving) and Kedes Hotel are live; Chrisyn is in development." },
    { q: "Which stack?", a: "Next.js, TypeScript and JavaScript on the front, Node.js and FastAPI with Python on the back, PostgreSQL for data." },
    { q: "How do you use AI?", a: "To move faster on scaffolding, never to skip checking. I validate AI output with schema tests and authorization checks before it ships." },
    { q: "Where are you based?", a: "Abia State, Nigeria, working remotely. Languages: Igbo (native) and English (C1)." },
    { q: "Can we work together?", a: "Yes. I'm open to remote roles and contract projects. Email christianethelbert1@gmail.com and tell me what you're building." },
  ],
  projects: [
    { title: "Fortress Bank", tags: ["Live", "In development", "Fintech"], open: true,
      problem: "Money apps fail when accounts, currencies and identity are bolted on late. This one treats them as the core.",
      built: "A multi-currency demo banking platform with biometric authentication and virtual balances, funded by an admin. Designed to scale as usage grows.",
      statusText: "Live and still in active development. Next up: moving the data layer from Firebase to PostgreSQL, a full UI redesign, proper documentation and finalised legal pages.",
      stack: "Next.js, Node.js, Firebase (migrating to PostgreSQL)",
      linkLabel: "fortressbank-gray.vercel.app →", linkUrl: "https://fortressbank-gray.vercel.app" },
    { title: "Kedes Hotel", tags: ["Live", "Client contract"], open: false,
      problem: "A hotel needed guests to book rooms online without phone calls.",
      built: "A production booking platform delivered as a paid contract project, built and launched by me alone.",
      statusText: "", stack: "Full-stack web, deployed and live",
      linkLabel: "Kedesthotel.com →", linkUrl: "https://Kedesthotel.com" },
    { title: "Chrisyn", tags: ["In development", "SaaS"], open: false,
      problem: "Schools juggle admissions, records and roles across scattered tools.",
      built: "A school management system with separate views and permissions for each role.",
      statusText: "Under active development and not yet deployed. I only list live work as live.",
      stack: "Next.js, FastAPI, PostgreSQL", linkLabel: "", linkUrl: "" },
  ],
  stack: [
    { group: "Frontend", tags: ["Next.js", "HTML/CSS"] },
    { group: "Languages", tags: ["TypeScript", "JavaScript", "Python", "Bash"] },
    { group: "Backend", tags: ["Node.js", "FastAPI", "Pydantic", "REST APIs"] },
    { group: "Data", tags: ["PostgreSQL", "SQLAlchemy"] },
    { group: "Practice", tags: ["RBAC", "Auth", "AI-assisted dev"] },
  ],
  timeline: [
    { when: "Sept 2022 to Aug 2023", what: "Trained in software development at Jenga Tech." },
    { when: "2023 to 2024", what: "Built small projects, then paused development to find paid work." },
    { when: "Feb 2025", what: "Returned to building full time." },
    { when: "2026", what: "Shipped Fortress Bank and Kedes Hotel to production. Chrisyn is in development. Taught HTML and CSS to beginners along the way." },
  ],
  principles: [
    { title: "Secure by default", text: "Ownership rules, role checks and proper error codes come first, not last." },
    { title: "Honest scope", text: "I say what is live, what is in progress and what I haven't done." },
    { title: "AI with guardrails", text: "I use AI to speed up scaffolding, then check the output with schema tests and authorization checks." },
  ],
  contact: { note: "Languages: Igbo (native), English (C1). Open to remote roles.", demoLabel: "Live demo", demoUrl: "https://fortressbank-gray.vercel.app" },
  socials: [
    { label: "LinkedIn", url: "https://www.linkedin.com/in/christian-ethelbert-005217408/" },
    { label: "GitHub", url: "https://github.com/Chrisboi242-242" },
    { label: "X / Twitter", url: "https://x.com/chris_ethel121" },
    { label: "TikTok", url: "https://www.tiktok.com/@christian_ethelbert" },
  ],
};
